### ISSUE TITLE
does it support Arabic language? RTL

### ISSUE THREAD

**Issue by adals** [imgui-rs/imgui-rs#72] opened 2017-08-28 20:13 UTC
hello and thanks for your work 
i want to ask that does it support Arabic language? RTL and how?

because when i write a word like مرحبا  it shows like ????????

**Comment by Gekkio** [comment] 2017-08-29 07:40
Hi,

It looks like [imgui doesn't support RTL](https://github.com/ocornut/imgui/issues/1228) so unfortunately imgui-rs can't support it either. The question marks are caused by a different issue: the default font is missing a lot of characters. The font issue can be fixed by adding support for custom fonts, but RTL support can't be added to imgui-rs unless imgui adds some RTL support.

**Comment by dbr** [comment] 2022-01-18 00:11
Closing old issue, as as upstream issue is also closed, and the missing font-glyph-ranges part is answered above

**Closed by dbr** 2022-01-18 00:11 UTC
