### ISSUE TITLE
ResetRenderState memory leak in glow-renderer

### ISSUE THREAD

**Issue by Selicre** [imgui-rs/imgui-rs#643] opened 2022-05-13 18:34 UTC
When resetting the renderer, it doesn't clean up the allocated VAO. To fix this, simply delete the allocated VAO when setting up render state. Not sure if this has side effects, you might want to change it to an Option and only delete it when it is Some.

```rust
#[cfg(feature = "bind_vertex_array_support")]
if self.gl_version.bind_vertex_array_support() {
    unsafe {
        gl.delete_vertex_array(self.vertex_array_object);    // add this line
        self.vertex_array_object = gl
            .create_vertex_array()
            .map_err(|err| format!("Error creating vertex array object: {}", err))?;
        gl.bind_vertex_array(Some(self.vertex_array_object));
    }
}

```

https://github.com/imgui-rs/imgui-rs/blob/main/imgui-glow-renderer/src/lib.rs#L402

**Comment by dbr** [comment] 2022-05-16 04:16
I'm not particularly familiar with this code, so could very well be wrong, but..

The `vertex_array_object` seems to be deleted in the `Renderer::render()` method here:

https://github.com/imgui-rs/imgui-rs/blob/f58744e57949ade294d87fc9798502675a2fd4d5/imgui-glow-renderer/src/lib.rs#L320

However it still seems plausible that `render` might not get called and it could leak

Looking at the glow-rs hello-world example, the method is called on the CloseRequested event handler, which is different to what we do (and different to the proposed fix):
https://github.com/grovesNL/glow/blob/6108fdf81cf4c2a64facc769b0a58b8ff2b859ce/examples/hello/src/main.rs#L152

Our glow-renderer does have a destroy method called via `Drop` which might be a more appropriate place to call this, but no idea if that would work like I assume?

:shrug:

@jmaargh @sanbox-irl ?

**Comment by jmaargh** [comment] 2022-05-16 09:41
I don't think re-creating the VAO every frame is typical in OpenGL, but is done here for simplicity of integration to other renderers. See also [this comment](https://github.com/ocornut/imgui/blob/fe245914114588f272b0924538fdd43f6c127a26/backends/imgui_impl_opengl3.cpp#L384) from the upstream example this renderer follows.

This is, however, a good catch. Since I put [the creation of the VAO](https://github.com/imgui-rs/imgui-rs/blob/f58744e57949ade294d87fc9798502675a2fd4d5/imgui-glow-renderer/src/lib.rs#L402) in `Renderer::set_up_render_state` (which is `pub`) and the [deletion of it](https://github.com/imgui-rs/imgui-rs/blob/f58744e57949ade294d87fc9798502675a2fd4d5/imgui-glow-renderer/src/lib.rs#L320) in `Renderer::render` they are asymmetric and it's possible for somebody to manually call `set_up_render_state` without then calling `render`.

I think the solution should be to simply move the VAO creation to `Renderer::render` (immediately before the call to `self.set_up_render_state( ... )`). This also matches the upstream example better.

---

This is a good catch and should be fixed, but also users shouldn't expect the API of this example renderer to be foolproof. It was designed more for simplicity and control (allowing the user to manually have some control over the GL state) than as a production-ready fully-general API. This control is why so many things are `pub`.

**Closed** 2022-05-31 22:28 UTC
