### ISSUE TITLE
[imgui-winit-support] Double input characters in .. everything?

### ISSUE THREAD

**Issue by sarchar** [imgui-rs/imgui-rs#792] opened 2024-09-25 08:56 UTC
**Describe the bug**
input_text() widgets receive input characters for both key pressed and key released events.  The problem seems to stem from the code at https://github.com/imgui-rs/imgui-rs/blob/67f7f11363e62f09aa0e1288a17800e505860486/imgui-winit-support/src/lib.rs#L467C1-L473C18 --

```rust
                if let Some(txt) = &event.text {
                    for ch in txt.chars() {
                        if ch != '\u{7f}' {
                            io.add_input_character(ch)
                        }
                    }
                }
```

which *seems* like it should be wrapped in a check on `event.state`.  I'm reluctant to make a PR because I have a hard time believing this issue has gone 9 months without being noticed and am assuming it's actually an issue on my end.  In my fork of this branch, I added a check for Pressed and the issue does go away.

Can anyone reproduce this?

**To Reproduce**
Press keys in an input_text() widget.

**Expected behavior**
Only one character should be added to the field.

**Screenshots**
After typing `abc`:
![image](https://github.com/user-attachments/assets/1d5f65cf-13de-4618-b03b-a513bd1dee09)

**Please describe your environment**
This happens with the current main branch on Linux using imgui-winit-support.

**Comment by mororo18** [comment] 2024-09-25 21:52
the same as #776

**Comment by mororo18** [comment] 2024-09-26 02:21
There is an inconsistency in the text field of `KeyEvent` during key release on Windows and Linux (WSL).

```
wsl:
KeyEvent { physical_key: Code(KeyD), logical_key: Character("d"), text: Some("d"), location: Standard, state: Pressed,  repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("d"), text_with_all_modifiers: Some("d") } }
KeyEvent { physical_key: Code(KeyD), logical_key: Character("d"), text: Some("d"), location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { key_without_modifiers: Character("d"), text_with_all_modifiers: Some("d") } }

windows:
KeyEvent { physical_key: Code(KeyD), logical_key: Character("d"), text: Some("d"), location: Standard, state: Pressed,  repeat: false, platform_specific: KeyEventExtra { text_with_all_modifers: Some("d"), key_without_modifiers: Character("d") } }
KeyEvent { physical_key: Code(KeyD), logical_key: Character("d"), text: None,      location: Standard, state: Released, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifers: None,      key_without_modifiers: Character("d") } }

```

**Comment by sarchar** [comment] 2024-09-26 03:26
I'm on X11, for what it's worth.

And yeah, looks like a duplicate bug.

**Comment by sanbox-irl** [comment] 2024-09-26 13:44
closing as a dupe of #776 -- and yeah, in general, we're way less tested on linux than we are on windows or even macOS. That mostly has to do with the crop of maintainers and the game orientation of the library, but mostly because we haven't invested in mocking up input related CI so we don't have much testing on that.

**Closed by sanbox-irl** 2024-09-26 13:44 UTC
