### ISSUE TITLE
imgui-sys version not match

### ISSUE THREAD

**Issue by ScottHuangZL** [imgui-rs/imgui-rs#8] opened 2015-09-03 01:56 UTC
I try to delete my old imgui-rs folder(it success build and run sample already), and git clone from git hub again to use latest versions.
# Issue:

imgui-sys
version required:^0.0.2
version found: 0.0.3-pre

After I change to 
[dependencies.imgui-sys]
path = "imgui-sys"
version = "*"

It can build again.

However, the output sample exe cannot run smoothly.
The hello_world.exe will crash when I open it. Thanks.
Can you help on it? Thanks.

**Comment by Gekkio** [comment] 2015-09-03 05:08
Sorry about the version mismatch, it's now fixed.

Can you tell me more about the crash? Do you get any error message?
Try running it from the command line. The program probably panics and will display an error in the command line.

**Comment by ScottHuangZL** [comment] 2015-09-03 05:21
Thanks for your quickly response.  The error like below:

glium has triggered an OpenGL error during initialization. Please report this error: https://github.com/tomaka/glium/issues.

**Comment by Gekkio** [comment] 2015-09-03 14:34
Ok, could you copy and paste the full command-line output? Is there any warnings or text about program panic?

**Comment by ScottHuangZL** [comment] 2015-09-03 15:52
I try:
Cargo clean
Cargo test
success build with below info, however, program will be crash when use 
Cargo run --example hello_world, I also attach the error info below.

=====success for cargo test=====
   Compiling gdi32-sys v0.1.1
   Compiling winapi v0.2.2
   Compiling lazy_static v0.1.14
   Compiling khronos_api v0.0.8
   Compiling winapi-build v0.1.1
   Compiling bitflags v0.3.2
   Compiling libc v0.1.10
   Compiling smallvec v0.1.5
   Compiling khronos_api v0.0.7
   Compiling dwmapi-sys v0.1.0
   Compiling advapi32-sys v0.1.2
   Compiling user32-sys v0.1.2
   Compiling kernel32-sys v0.1.4
   Compiling shell32-sys v0.1.1
   Compiling xml-rs v0.1.26
   Compiling shared_library v0.1.0
   Compiling log v0.3.2
   Compiling gl_common v0.0.4
   Compiling gl_generator v0.0.26
   Compiling gl_generator v0.0.25
   Compiling glium v0.8.7
   Compiling glutin v0.3.5
   Compiling gcc v0.3.13
   Compiling time v0.1.32
   Compiling imgui-sys v0.0.3-pre (file:///C:/personal/Rust/projects/imgui-rs)
   Compiling imgui v0.0.3-pre (file:///C:/personal/Rust/projects/imgui-rs)
     Running C:\personal\Rust\projects\imgui-rs\target\debug\imgui-1e87ac4ff3ea550e.exe

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

   Doc-tests imgui

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

[Finished in 76.8s]

=========Below are Crash Info when use cargo run --example hello_world ==========
     Running `C:\personal\Rust\projects\imgui-rs\target\debug\examples\hello_world.exe`
glium has triggered an OpenGL error during initialization. Please report this error: https://github.com/tomaka/glium/issues
An unknown error occurred

I try to debug program in Visual Studio, and it show info as 1st error:
Unhandled exception at 0x0082e940 in hello_world.exe: 0xC000001D: Illegal Instruction.

**Comment by Gekkio** [comment] 2015-09-07 15:25
Thanks! You're probably right, the glium message is just a warning and the crash is caused by imgui-rs.
What kind of CPU and GPU are you using?

**Comment by ScottHuangZL** [comment] 2015-09-08 01:16
CPU: Intel i7 3540
Display adapter: Intel HD graphics 4000

As you know I can run imgui-rs smoothly with rust 1.2 32 bit stable version several days ago. So, may be this issue caused by rust nightly 64 bit version have some subtle bug.   64 bit version may be not optimized well.

I cannot share more info than below:
The compiler can compile the program, there will be a window show up when I cargo run the hello_world or test_window, however, it did not show contents in that window, and after a while it crashed and the console say "An unknown error occurred".

**Comment by ScottHuangZL** [comment] 2015-09-24 14:51
Could you have a time to look into it? Thanks.

**Comment by Gekkio** [comment] 2015-09-26 12:47
Sorry, I haven't been able to reproduce the problem. I've tried some Win 10 + Nvidia machines and one laptop with Win 10 + 1st generation i5, but imgui-rs examples work fine on those machines.

Could you try Rust 1.3?

**Comment by ScottHuangZL** [comment] 2015-09-27 11:02
I am try build it with Rust 1.3 stable 64 bit
below are the error info:
error: linking with `gcc` failed: exit code: 1
......
note: C:\personal\Rust\projects\imgui-rs\target\debug\deps\libimgui_sys-ee92b681299ce70d.rlib(imgui.o): In function `ImeSetInputScreenPosFn_DefaultImpl':
C:\personal\Rust\projects\imgui-rs\imgui-sys/third-party/cimgui/imgui/imgui.cpp:9004: undefined reference to `ImmGetContext'
C:\personal\Rust\projects\imgui-rs\imgui-sys/third-party/cimgui/imgui/imgui.cpp:9010: undefined reference to `ImmSetCompositionWindow'

error: aborting due to previous error
Could not compile `imgui`

**Comment by CryZe** [comment] 2016-06-18 23:33
This seems to happen because imgui-rs doesn't properly link against imm.dll

**Closed** 2022-11-28 07:20 UTC
